### ISSUE TITLE
Error while building library  jar 

### ISSUE THREAD

**Issue by Animeshm77** [Grover-c13/PokeGOAPI-Java#665]
Error :-

$ ./gradlew :library:build --stacktrace
You are using Gradle 3.0:  This version of the protobuf plugin works with Gradle version 2.12+
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
:library:extractIncludeProto UP-TO-DATE
:library:extractProto UP-TO-DATE
:library:generateProto UP-TO-DATE
:library:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.7
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\device\DeviceInfo.java:21: error: package POGOProtos.Networking.Envelopes does not exist
import POGOProtos.Networking.Envelopes.SignatureOuterClass;
                                      ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\device\DeviceInfo.java:88: error: package SignatureOuterClass.Signature.DeviceInfo does not exist
        private SignatureOuterClass.Signature.DeviceInfo.Builder deviceInfoBuilder;
                                                        ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\device\DeviceInfo.java:292: error: package SignatureOuterClass.Signature does not exist
        public SignatureOuterClass.Signature.DeviceInfo getDeviceInfo() {
                                            ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\device\SensorInfo.java:18: error: package POGOProtos.Networking.Envelopes does not exist
import POGOProtos.Networking.Envelopes.SignatureOuterClass;
                                      ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\device\SensorInfo.java:26: error: package SignatureOuterClass.Signature.SensorInfo does not exist
        private SignatureOuterClass.Signature.SensorInfo.Builder sensorInfoBuilder;
                                                        ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\device\SensorInfo.java:188: error: package SignatureOuterClass.Signature does not exist
        public SignatureOuterClass.Signature.SensorInfo getSensorInfo() {
                                            ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:18: error: package POGOProtos.Data.Battle.BattleActionOuterClass does not exist
import POGOProtos.Data.Battle.BattleActionOuterClass.BattleAction;
                                                    ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:19: error: package POGOProtos.Data.Battle does not exist
import POGOProtos.Data.Battle.BattleActionTypeOuterClass;
                             ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:20: error: package POGOProtos.Data.Battle.BattlePokemonInfoOuterClass does not exist
import POGOProtos.Data.Battle.BattlePokemonInfoOuterClass.BattlePokemonInfo;
                                                         ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:21: error: package POGOProtos.Data.Battle.BattleStateOuterClass does not exist
import POGOProtos.Data.Battle.BattleStateOuterClass.BattleState;
                                                   ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:22: error: package POGOProtos.Data does not exist
import POGOProtos.Data.PokemonDataOuterClass;
                      ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:23: error: package POGOProtos.Networking.Requests.Messages.AttackGymMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.AttackGymMessageOuterClass.AttackGymMessage;
                                                                         ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:24: error: package POGOProtos.Networking.Requests.Messages does not exist
import POGOProtos.Networking.Requests.Messages.StartGymBattleMessageOuterClass;
                                              ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:25: error: package POGOProtos.Networking.Requests.Messages.StartGymBattleMessageOuterClass.StartGymBattleMessage does not exist
import POGOProtos.Networking.Requests.Messages.StartGymBattleMessageOuterClass.StartGymBattleMessage.Builder;
                                                                                                    ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:26: error: package POGOProtos.Networking.Requests.RequestTypeOuterClass does not exist
import POGOProtos.Networking.Requests.RequestTypeOuterClass.RequestType;
                                                           ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:27: error: package POGOProtos.Networking.Responses.AttackGymResponseOuterClass does not exist
import POGOProtos.Networking.Responses.AttackGymResponseOuterClass.AttackGymResponse;
                                                                  ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:28: error: package POGOProtos.Networking.Responses.StartGymBattleResponseOuterClass does not exist
import POGOProtos.Networking.Responses.StartGymBattleResponseOuterClass.StartGymBattleResponse;
                                                                       ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:29: error: package POGOProtos.Networking.Responses.StartGymBattleResponseOuterClass.StartGymBattleResponse does not exist
import POGOProtos.Networking.Responses.StartGymBattleResponseOuterClass.StartGymBattleResponse.Result;
                                                                                              ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:18: error: package POGOProtos.Data.Gym.GymMembershipOuterClass does not exist
import POGOProtos.Data.Gym.GymMembershipOuterClass.GymMembership;
                                                  ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:19: error: package POGOProtos.Data.PokemonDataOuterClass does not exist
import POGOProtos.Data.PokemonDataOuterClass.PokemonData;
                                            ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:20: error: package POGOProtos.Enums does not exist
import POGOProtos.Enums.PokemonIdOuterClass;
                       ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:21: error: package POGOProtos.Enums does not exist
import POGOProtos.Enums.TeamColorOuterClass;
                       ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:22: error: package POGOProtos.Map.Fort.FortDataOuterClass does not exist
import POGOProtos.Map.Fort.FortDataOuterClass.FortData;
                                             ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:23: error: package POGOProtos.Networking.Requests.Messages.GetGymDetailsMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.GetGymDetailsMessageOuterClass.GetGymDetailsMessage;
                                                                             ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:24: error: package POGOProtos.Networking.Requests.RequestTypeOuterClass does not exist
import POGOProtos.Networking.Requests.RequestTypeOuterClass.RequestType;
                                                           ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:25: error: package POGOProtos.Networking.Responses.GetGymDetailsResponseOuterClass does not exist
import POGOProtos.Networking.Responses.GetGymDetailsResponseOuterClass.GetGymDetailsResponse;
                                                                      ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:32: error: package POGOProtos.Data.PokemonDataOuterClass does not exist
import POGOProtos.Data.PokemonDataOuterClass.PokemonData;
                                            ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:33: error: package POGOProtos.Inventory.Item.ItemIdOuterClass does not exist
import POGOProtos.Inventory.Item.ItemIdOuterClass.ItemId;
                                                 ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:34: error: package POGOProtos.Networking.Requests.Messages.EvolvePokemonMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.EvolvePokemonMessageOuterClass.EvolvePokemonMessage;
                                                                             ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:35: error: package POGOProtos.Networking.Requests.Messages.NicknamePokemonMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.NicknamePokemonMessageOuterClass.NicknamePokemonMessage;
                                                                               ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:36: error: package POGOProtos.Networking.Requests.Messages.ReleasePokemonMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.ReleasePokemonMessageOuterClass.ReleasePokemonMessage;
                                                                              ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:37: error: package POGOProtos.Networking.Requests.Messages.SetFavoritePokemonMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.SetFavoritePokemonMessageOuterClass.SetFavoritePokemonMessage;
                                                                                  ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:38: error: package POGOProtos.Networking.Requests.Messages.UpgradePokemonMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.UpgradePokemonMessageOuterClass.UpgradePokemonMessage;
                                                                              ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:39: error: package POGOProtos.Networking.Requests.Messages does not exist
import POGOProtos.Networking.Requests.Messages.UseItemPotionMessageOuterClass;
                                              ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:40: error: package POGOProtos.Networking.Requests.Messages does not exist
import POGOProtos.Networking.Requests.Messages.UseItemReviveMessageOuterClass;
                                              ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:41: error: package POGOProtos.Networking.Requests.RequestTypeOuterClass does not exist
import POGOProtos.Networking.Requests.RequestTypeOuterClass.RequestType;
                                                           ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:42: error: package POGOProtos.Networking.Responses.EvolvePokemonResponseOuterClass does not exist
import POGOProtos.Networking.Responses.EvolvePokemonResponseOuterClass.EvolvePokemonResponse;
                                                                      ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:43: error: package POGOProtos.Networking.Responses.NicknamePokemonResponseOuterClass does not exist
import POGOProtos.Networking.Responses.NicknamePokemonResponseOuterClass.NicknamePokemonResponse;
                                                                        ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:44: error: package POGOProtos.Networking.Responses.ReleasePokemonResponseOuterClass does not exist
import POGOProtos.Networking.Responses.ReleasePokemonResponseOuterClass.ReleasePokemonResponse;
                                                                       ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:45: error: package POGOProtos.Networking.Responses.ReleasePokemonResponseOuterClass.ReleasePokemonResponse does not exist
import POGOProtos.Networking.Responses.ReleasePokemonResponseOuterClass.ReleasePokemonResponse.Result;
                                                                                              ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:46: error: package POGOProtos.Networking.Responses.SetFavoritePokemonResponseOuterClass does not exist
import POGOProtos.Networking.Responses.SetFavoritePokemonResponseOuterClass.SetFavoritePokemonResponse;
                                                                           ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:47: error: package POGOProtos.Networking.Responses.UpgradePokemonResponseOuterClass does not exist
import POGOProtos.Networking.Responses.UpgradePokemonResponseOuterClass.UpgradePokemonResponse;
                                                                       ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:48: error: package POGOProtos.Networking.Responses.UseItemPotionResponseOuterClass does not exist
import POGOProtos.Networking.Responses.UseItemPotionResponseOuterClass.UseItemPotionResponse;
                                                                      ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:49: error: package POGOProtos.Networking.Responses.UseItemReviveResponseOuterClass does not exist
import POGOProtos.Networking.Responses.UseItemReviveResponseOuterClass.UseItemReviveResponse;
                                                                      ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:9: error: package POGOProtos.Data.PokemonDataOuterClass does not exist
import POGOProtos.Data.PokemonDataOuterClass.PokemonData;
                                            ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:10: error: package POGOProtos.Enums does not exist
import POGOProtos.Enums.PokemonFamilyIdOuterClass;
                       ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:11: error: package POGOProtos.Enums does not exist
import POGOProtos.Enums.PokemonIdOuterClass;
                       ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:12: error: package POGOProtos.Enums.PokemonMoveOuterClass does not exist
import POGOProtos.Enums.PokemonMoveOuterClass.PokemonMove;
                                             ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:13: error: package POGOProtos.Inventory.Item.ItemIdOuterClass does not exist
import POGOProtos.Inventory.Item.ItemIdOuterClass.ItemId;
                                                 ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:17: error: package POGOProtos.Enums.PokemonIdOuterClass does not exist
import static POGOProtos.Enums.PokemonIdOuterClass.PokemonId.EEVEE;
                                                  ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:17: error: static import only from classes and interfaces
import static POGOProtos.Enums.PokemonIdOuterClass.PokemonId.EEVEE;
^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:18: error: package POGOProtos.Enums.PokemonIdOuterClass does not exist
import static POGOProtos.Enums.PokemonIdOuterClass.PokemonId.FLAREON;
                                                  ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:18: error: static import only from classes and interfaces
import static POGOProtos.Enums.PokemonIdOuterClass.PokemonId.FLAREON;
^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:19: error: package POGOProtos.Enums.PokemonIdOuterClass does not exist
import static POGOProtos.Enums.PokemonIdOuterClass.PokemonId.JOLTEON;
                                                  ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:19: error: static import only from classes and interfaces
import static POGOProtos.Enums.PokemonIdOuterClass.PokemonId.JOLTEON;
^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:20: error: package POGOProtos.Enums.PokemonIdOuterClass does not exist
import static POGOProtos.Enums.PokemonIdOuterClass.PokemonId.VAPOREON;
                                                  ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:20: error: static import only from classes and interfaces
import static POGOProtos.Enums.PokemonIdOuterClass.PokemonId.VAPOREON;
^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:46: error: cannot find symbol
        private List<BattlePokemonInfo> bteam;
                     ^
  symbol:   class BattlePokemonInfo
  location: class Battle
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:47: error: cannot find symbol
        private StartGymBattleResponse battleResponse;
                ^
  symbol:   class StartGymBattleResponse
  location: class Battle
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\PokemonGo.java:18: error: package POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass.RequestEnvelope does not exist
import POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass.RequestEnvelope.AuthInfo;
                                                                                ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\PokemonGo.java:19: error: package POGOProtos.Networking.Envelopes does not exist
import POGOProtos.Networking.Envelopes.SignatureOuterClass;
                                      ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:52: error: cannot find symbol
        @Getter
        ^
  symbol:   class BattleState
  location: class Battle
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:82: error: cannot find symbol
        public Result start() throws LoginFailedException, RemoteServerException {
               ^
  symbol:   class Result
  location: class Battle
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:127: error: cannot find symbol
        public AttackGymResponse attack(int times) throws LoginFailedException, RemoteServerException {
               ^
  symbol:   class AttackGymResponse
  location: class Battle
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:155: error: cannot find symbol
        private BattlePokemonInfo createBattlePokemon(Pokemon pokemon) {
                ^
  symbol:   class BattlePokemonInfo
  location: class Battle
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:171: error: package PokemonDataOuterClass does not exist
        private PokemonDataOuterClass.PokemonData getDefender(int index) throws LoginFailedException, RemoteServerException {
                                     ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:180: error: cannot find symbol
        private BattleAction getLastActionFromServer() {
                ^
  symbol:   class BattleAction
  location: class Battle
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:192: error: cannot find symbol
        private AttackGymResponse sendBlankAction() throws LoginFailedException, RemoteServerException {
                ^
  symbol:   class AttackGymResponse
  location: class Battle
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:219: error: cannot find symbol
        private AttackGymResponse doActions(List<BattleAction> actions) throws LoginFailedException, RemoteServerException {
                                                 ^
  symbol:   class BattleAction
  location: class Battle
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Battle.java:219: error: cannot find symbol
        private AttackGymResponse doActions(List<BattleAction> actions) throws LoginFailedException, RemoteServerException {
                ^
  symbol:   class AttackGymResponse
  location: class Battle
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:40: error: cannot find symbol
        private FortData proto;
                ^
  symbol:   class FortData
  location: class Gym
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:41: error: cannot find symbol
        private GetGymDetailsResponse details;
                ^
  symbol:   class GetGymDetailsResponse
  location: class Gym
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:50: error: cannot find symbol
        public Gym(PokemonGo api, FortData proto) {
                                  ^
  symbol:   class FortData
  location: class Gym
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:72: error: package TeamColorOuterClass does not exist
        public TeamColorOuterClass.TeamColor getOwnedByTeam() {
                                  ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:76: error: package PokemonIdOuterClass does not exist
        public PokemonIdOuterClass.PokemonId getGuardPokemonId() {
                                  ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:101: error: cannot find symbol
        private GetGymDetailsResponse details() throws LoginFailedException, RemoteServerException {
                ^
  symbol:   class GetGymDetailsResponse
  location: class Gym
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:135: error: package GetGymDetailsResponse does not exist
        public GetGymDetailsResponse.Result getResult() throws LoginFailedException, RemoteServerException {
                                    ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:149: error: cannot find symbol
        public List<GymMembership> getGymMembers() throws LoginFailedException, RemoteServerException {
                    ^
  symbol:   class GymMembership
  location: class Gym
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\gym\Gym.java:160: error: cannot find symbol
        public List<PokemonData> getDefendingPokemon() throws LoginFailedException, RemoteServerException {
                    ^
  symbol:   class PokemonData
  location: class Gym
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:71: error: cannot find symbol
        public Pokemon(PokemonGo api, PokemonData proto) {
                                      ^
  symbol:   class PokemonData
  location: class Pokemon
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:83: error: cannot find symbol
        public Result transferPokemon() throws LoginFailedException, RemoteServerException {
               ^
  symbol:   class Result
  location: class Pokemon
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:115: error: package NicknamePokemonResponse does not exist
        public NicknamePokemonResponse.Result renamePokemon(String nickname)
                                      ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:146: error: package SetFavoritePokemonResponse does not exist
        public SetFavoritePokemonResponse.Result setFavoritePokemon(boolean markFavorite)
                                         ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:217: error: package UpgradePokemonResponse does not exist
        public UpgradePokemonResponse.Result powerUp() throws LoginFailedException, RemoteServerException {
                                     ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:227: error: package UpgradePokemonResponse does not exist
        public Observable<UpgradePokemonResponse.Result> powerUpAsync() {
                                                ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\map\pokemon\EvolutionResult.java:18: error: package POGOProtos.Networking.Responses does not exist
import POGOProtos.Networking.Responses.EvolvePokemonResponseOuterClass;
                                      ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:303: error: package UseItemPotionResponse does not exist
        public UseItemPotionResponse.Result heal()
                                    ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:333: error: cannot find symbol
        public UseItemPotionResponse.Result usePotion(ItemId itemId)
                                                      ^
  symbol:   class ItemId
  location: class Pokemon
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:333: error: package UseItemPotionResponse does not exist
        public UseItemPotionResponse.Result usePotion(ItemId itemId)
                                    ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:369: error: package UseItemReviveResponse does not exist
        public UseItemReviveResponse.Result revive()
                                    ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:393: error: cannot find symbol
        public UseItemReviveResponse.Result useRevive(ItemId itemId)
                                                      ^
  symbol:   class ItemId
  location: class Pokemon
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:393: error: package UseItemReviveResponse does not exist
        public UseItemReviveResponse.Result useRevive(ItemId itemId)
                                    ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\EvolutionForm.java:5: error: package POGOProtos.Enums does not exist
import POGOProtos.Enums.PokemonIdOuterClass;
                       ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:27: error: cannot find symbol
        @Setter
        ^
  symbol:   class PokemonData
  location: class PokemonDetails
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonMeta.java:18: error: package POGOProtos.Enums.PokemonFamilyIdOuterClass does not exist
import POGOProtos.Enums.PokemonFamilyIdOuterClass.PokemonFamilyId;
                                                 ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonMeta.java:19: error: package POGOProtos.Enums.PokemonIdOuterClass does not exist
import POGOProtos.Enums.PokemonIdOuterClass.PokemonId;
                                           ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonMeta.java:20: error: package POGOProtos.Enums.PokemonMoveOuterClass does not exist
import POGOProtos.Enums.PokemonMoveOuterClass.PokemonMove;
                                             ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:31: error: cannot find symbol
        public PokemonDetails(PokemonGo api, PokemonData proto) {
                                             ^
  symbol:   class PokemonData
  location: class PokemonDetails
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:40: error: package PokemonFamilyIdOuterClass does not exist
        public PokemonFamilyIdOuterClass.PokemonFamilyId getPokemonFamily() {
                                        ^
D:\PokeGOAPI\library\src\main\java\com\pokegoapi\api\pokemon\PokemonDetails.java:44: error: cannot find symbol
        public PokemonData getDefaultInstanceForType() {
               ^
  symbol:   class PokemonData
  location: class PokemonDetails
100 errors
 FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':library:compileJava'.
  > Compilation failed; see the compiler error output for details.

**Comment by gionata-bisciari** [comment]
Try to reclone the repository, then `git submodule update --init` and `./gradlew :library:build`

**Comment by Animeshm77** [comment]
tried not working ...
any issue  here  ?

> :library:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.7

**Comment by gionata-bisciari** [comment]
This warning is ok

**Comment by iGio90** [comment]
Ci ho pensato io ez

**Comment by gionata-bisciari** [comment]
What is in  your PokeGOAPI-Java\library\src\resources\protobuf?
I seen they had de same problem #213 #192

**Comment by Animeshm77** [comment]
yeah problem fixed thanks !
