### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by jeremys18** [Grover-c13/PokeGOAPI-Java#919]
**Description:**
I have tried for days to build the latest library but can't get it to work. It fails every time.

**Steps to reproduce:**

Download the source and follow the steps in  "Build from source". Notice it fails.

**Expected behavior:**
It should build

**Actual behavior:**
It throws erros and fails to build.

**Stacktrace (If it's a crash):**
L:\PokeGOAPI-Java-Development>gradlew :library:build
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
You are using Gradle 3.0:  This version of the protobuf plugin works with Gradle version 2.12+
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
:library:extractIncludeProto
:library:extractProto
:library:generateProto UP-TO-DATE
:library:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\device\ActivityStatus.java:23: error: package POGOProtos.Networking.Envelopes does not exist
import POGOProtos.Networking.Envelopes.SignatureOuterClass;
                                      ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\device\ActivityStatus.java:31: error: package SignatureOuterClass.Signature.ActivityStatus does not exist
        private SignatureOuterClass.Signature.ActivityStatus.Builder activityStatusBuilder;
                                                            ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\PokemonGo.java:18: error: package POGOProtos.Enums.TutorialStateOuterClass does not exist
import POGOProtos.Enums.TutorialStateOuterClass.TutorialState;
                                               ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\PokemonGo.java:19: error: package POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass.RequestEnvelope does not exist
import POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass.RequestEnvelope.AuthInfo;
                                                                                ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\PokemonGo.java:20: error: package POGOProtos.Networking.Envelopes does not exist
import POGOProtos.Networking.Envelopes.SignatureOuterClass;
                                      ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\PokemonGo.java:21: error: package POGOProtos.Networking.Requests.Messages.CheckChallengeMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.CheckChallengeMessageOuterClass.CheckChallengeMessage;
                                                                              ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\PokemonGo.java:22: error: package POGOProtos.Networking.Requests.Messages.GetAssetDigestMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.GetAssetDigestMessageOuterClass.GetAssetDigestMessage;
                                                                              ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\PokemonGo.java:23: error: package POGOProtos.Networking.Requests.Messages.LevelUpRewardsMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.LevelUpRewardsMessageOuterClass.LevelUpRewardsMessage;
                                                                              ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\PokemonGo.java:24: error: package POGOProtos.Networking.Requests.Messages.VerifyChallengeMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.VerifyChallengeMessageOuterClass.VerifyChallengeMessage;
                                                                               ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\PokemonGo.java:25: error: package POGOProtos.Networking.Requests.RequestTypeOuterClass does not exist
import POGOProtos.Networking.Requests.RequestTypeOuterClass.RequestType;
                                                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\PokemonGo.java:26: error: package POGOProtos.Networking.Responses.CheckChallengeResponseOuterClass does not exist
import POGOProtos.Networking.Responses.CheckChallengeResponseOuterClass.CheckChallengeResponse;
                                                                       ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\PokemonGo.java:27: error: package POGOProtos.Networking.Responses.DownloadRemoteConfigVersionResponseOuterClass does not exist
import POGOProtos.Networking.Responses.DownloadRemoteConfigVersionResponseOuterClass.DownloadRemoteConfigVersionResponse;
                                                                                    ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\PokemonGo.java:28: error: package POGOProtos.Networking.Responses.LevelUpRewardsResponseOuterClass does not exist
import POGOProtos.Networking.Responses.LevelUpRewardsResponseOuterClass.LevelUpRewardsResponse;
                                                                       ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\PokemonGo.java:29: error: package POGOProtos.Networking.Responses.LevelUpRewardsResponseOuterClass.LevelUpRewardsResponse does not exist
import POGOProtos.Networking.Responses.LevelUpRewardsResponseOuterClass.LevelUpRewardsResponse.Result;
                                                                                              ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\PokemonGo.java:30: error: package POGOProtos.Networking.Responses.VerifyChallengeResponseOuterClass does not exist
import POGOProtos.Networking.Responses.VerifyChallengeResponseOuterClass.VerifyChallengeResponse;
                                                                        ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\device\ActivityStatus.java:44: error: package SignatureOuterClass.Signature does not exist
        public static SignatureOuterClass.Signature.ActivityStatus getDefault(PokemonGo api, Random random) {
                                                   ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\device\ActivityStatus.java:99: error: package SignatureOuterClass.Signature.ActivityStatus does not exist
        public SignatureOuterClass.Signature.ActivityStatus.Builder getBuilder() {
                                                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\device\ActivityStatus.java:103: error: package SignatureOuterClass.Signature does not exist
        public SignatureOuterClass.Signature.ActivityStatus getActivityStatus() {
                                            ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\main\RequestHandler.java:18: error: package POGOProtos.Networking.Envelopes.AuthTicketOuterClass does not exist
import POGOProtos.Networking.Envelopes.AuthTicketOuterClass.AuthTicket;
                                                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\main\RequestHandler.java:19: error: package POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass does not exist
import POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass.RequestEnvelope;
                                                                ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\main\RequestHandler.java:20: error: package POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass.RequestEnvelope does not exist
import POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass.RequestEnvelope.PlatformRequest;
                                                                                ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\main\RequestHandler.java:21: error: package POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass.RequestEnvelope.PlatformRequest does not exist
import POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass.RequestEnvelope.PlatformRequest.Builder;
                                                                                                ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\main\RequestHandler.java:22: error: package POGOProtos.Networking.Envelopes.ResponseEnvelopeOuterClass does not exist
import POGOProtos.Networking.Envelopes.ResponseEnvelopeOuterClass.ResponseEnvelope;
                                                                 ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\main\RequestHandler.java:23: error: package POGOProtos.Networking.Envelopes.ResponseEnvelopeOuterClass.ResponseEnvelope does not exist
import POGOProtos.Networking.Envelopes.ResponseEnvelopeOuterClass.ResponseEnvelope.PlatformResponse;
                                                                                  ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\main\RequestHandler.java:24: error: package POGOProtos.Networking.Envelopes.ResponseEnvelopeOuterClass.ResponseEnvelope does not exist
import POGOProtos.Networking.Envelopes.ResponseEnvelopeOuterClass.ResponseEnvelope.StatusCode;
                                                                                  ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\main\RequestHandler.java:25: error: package POGOProtos.Networking.Requests.RequestOuterClass does not exist
import POGOProtos.Networking.Requests.RequestOuterClass.Request;
                                                       ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\main\RequestHandler.java:26: error: package POGOProtos.Networking.Requests.RequestTypeOuterClass does not exist
import POGOProtos.Networking.Requests.RequestTypeOuterClass.RequestType;
                                                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\main\RequestHandler.java:27: error: package POGOProtos.Networking.Responses.GetPlayerResponseOuterClass does not exist
import POGOProtos.Networking.Responses.GetPlayerResponseOuterClass.GetPlayerResponse;
                                                                  ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:18: error: package POGOProtos.Data.Player does not exist
import POGOProtos.Data.Player.CurrencyOuterClass;
                             ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:19: error: package POGOProtos.Data.Player does not exist
import POGOProtos.Data.Player.PlayerStatsOuterClass;
                             ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:20: error: package POGOProtos.Data.PlayerBadgeOuterClass does not exist
import POGOProtos.Data.PlayerBadgeOuterClass.PlayerBadge;
                                            ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:21: error: package POGOProtos.Data.PlayerDataOuterClass does not exist
import POGOProtos.Data.PlayerDataOuterClass.PlayerData;
                                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:22: error: package POGOProtos.Enums.BadgeTypeOuterClass does not exist
import POGOProtos.Enums.BadgeTypeOuterClass.BadgeType;
                                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:23: error: package POGOProtos.Enums does not exist
import POGOProtos.Enums.TutorialStateOuterClass;
                       ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:24: error: package POGOProtos.Networking.Requests.Messages.CheckAwardedBadgesMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.CheckAwardedBadgesMessageOuterClass.CheckAwardedBadgesMessage;
                                                                                  ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:25: error: package POGOProtos.Networking.Requests.Messages.ClaimCodenameMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.ClaimCodenameMessageOuterClass.ClaimCodenameMessage;
                                                                             ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:26: error: package POGOProtos.Networking.Requests.Messages.EncounterTutorialCompleteMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.EncounterTutorialCompleteMessageOuterClass.EncounterTutorialCompleteMessage;
                                                                                         ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:27: error: package POGOProtos.Networking.Requests.Messages.GetPlayerMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.GetPlayerMessageOuterClass.GetPlayerMessage;
                                                                         ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:28: error: package POGOProtos.Networking.Requests.Messages.GetPlayerProfileMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.GetPlayerProfileMessageOuterClass.GetPlayerProfileMessage;
                                                                                ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:29: error: package POGOProtos.Networking.Requests.Messages.LevelUpRewardsMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.LevelUpRewardsMessageOuterClass.LevelUpRewardsMessage;
                                                                              ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:30: error: package POGOProtos.Networking.Requests.Messages.MarkTutorialCompleteMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.MarkTutorialCompleteMessageOuterClass.MarkTutorialCompleteMessage;
                                                                                    ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:31: error: package POGOProtos.Networking.Requests.Messages.SetAvatarMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.SetAvatarMessageOuterClass.SetAvatarMessage;
                                                                         ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:32: error: package POGOProtos.Networking.Requests.Messages does not exist
import POGOProtos.Networking.Requests.Messages.SetBuddyPokemonMessageOuterClass;
                                              ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:33: error: package POGOProtos.Networking.Requests.RequestTypeOuterClass does not exist
import POGOProtos.Networking.Requests.RequestTypeOuterClass.RequestType;
                                                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:34: error: package POGOProtos.Networking.Responses.CheckAwardedBadgesResponseOuterClass does not exist
import POGOProtos.Networking.Responses.CheckAwardedBadgesResponseOuterClass.CheckAwardedBadgesResponse;
                                                                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:35: error: package POGOProtos.Networking.Responses.ClaimCodenameResponseOuterClass does not exist
import POGOProtos.Networking.Responses.ClaimCodenameResponseOuterClass.ClaimCodenameResponse;
                                                                      ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:36: error: package POGOProtos.Networking.Responses.GetPlayerProfileResponseOuterClass does not exist
import POGOProtos.Networking.Responses.GetPlayerProfileResponseOuterClass.GetPlayerProfileResponse;
                                                                         ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:37: error: package POGOProtos.Networking.Responses.GetPlayerResponseOuterClass does not exist
import POGOProtos.Networking.Responses.GetPlayerResponseOuterClass.GetPlayerResponse;
                                                                  ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:38: error: package POGOProtos.Networking.Responses.LevelUpRewardsResponseOuterClass does not exist
import POGOProtos.Networking.Responses.LevelUpRewardsResponseOuterClass.LevelUpRewardsResponse;
                                                                       ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:39: error: package POGOProtos.Networking.Responses.MarkTutorialCompleteResponseOuterClass does not exist
import POGOProtos.Networking.Responses.MarkTutorialCompleteResponseOuterClass.MarkTutorialCompleteResponse;
                                                                             ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:40: error: package POGOProtos.Networking.Responses.SetAvatarResponseOuterClass does not exist
import POGOProtos.Networking.Responses.SetAvatarResponseOuterClass.SetAvatarResponse;
                                                                  ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:41: error: package POGOProtos.Networking.Responses.SetBuddyPokemonResponseOuterClass does not exist
import POGOProtos.Networking.Responses.SetBuddyPokemonResponseOuterClass.SetBuddyPokemonResponse;
                                                                        ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\inventory\Inventories.java:18: error: package POGOProtos.Data.PokemonDataOuterClass does not exist
import POGOProtos.Data.PokemonDataOuterClass.PokemonData;
                                            ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\inventory\Inventories.java:19: error: package POGOProtos.Enums.PokemonFamilyIdOuterClass does not exist
import POGOProtos.Enums.PokemonFamilyIdOuterClass.PokemonFamilyId;
                                                 ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\inventory\Inventories.java:20: error: package POGOProtos.Enums.PokemonIdOuterClass does not exist
import POGOProtos.Enums.PokemonIdOuterClass.PokemonId;
                                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\inventory\Inventories.java:21: error: package POGOProtos.Inventory.AppliedItemOuterClass does not exist
import POGOProtos.Inventory.AppliedItemOuterClass.AppliedItem;
                                                 ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\inventory\Inventories.java:22: error: package POGOProtos.Inventory.AppliedItemsOuterClass does not exist
import POGOProtos.Inventory.AppliedItemsOuterClass.AppliedItems;
                                                  ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\inventory\Inventories.java:23: error: package POGOProtos.Inventory.CandyOuterClass does not exist
import POGOProtos.Inventory.CandyOuterClass.Candy;
                                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\inventory\Inventories.java:24: error: package POGOProtos.Inventory does not exist
import POGOProtos.Inventory.EggIncubatorOuterClass;
                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\inventory\Inventories.java:25: error: package POGOProtos.Inventory.EggIncubatorsOuterClass does not exist
import POGOProtos.Inventory.EggIncubatorsOuterClass.EggIncubators;
                                                   ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\inventory\Inventories.java:26: error: package POGOProtos.Inventory.InventoryItemDataOuterClass does not exist
import POGOProtos.Inventory.InventoryItemDataOuterClass.InventoryItemData;
                                                       ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\inventory\Inventories.java:27: error: package POGOProtos.Inventory.InventoryItemOuterClass does not exist
import POGOProtos.Inventory.InventoryItemOuterClass.InventoryItem;
                                                   ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\inventory\Inventories.java:28: error: package POGOProtos.Inventory.Item.ItemDataOuterClass does not exist
import POGOProtos.Inventory.Item.ItemDataOuterClass.ItemData;
                                                   ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\inventory\Inventories.java:29: error: package POGOProtos.Inventory.Item.ItemIdOuterClass does not exist
import POGOProtos.Inventory.Item.ItemIdOuterClass.ItemId;
                                                 ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\inventory\Inventories.java:30: error: package POGOProtos.Networking.Requests.Messages.GetInventoryMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.GetInventoryMessageOuterClass.GetInventoryMessage;
                                                                            ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\inventory\Inventories.java:31: error: package POGOProtos.Networking.Requests does not exist
import POGOProtos.Networking.Requests.RequestTypeOuterClass;
                                     ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\inventory\Inventories.java:32: error: package POGOProtos.Networking.Responses.GetInventoryResponseOuterClass does not exist
import POGOProtos.Networking.Responses.GetInventoryResponseOuterClass.GetInventoryResponse;
                                                                     ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\auth\CredentialProvider.java:18: error: package POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass.RequestEnvelope does not exist
import POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass.RequestEnvelope.AuthInfo;
                                                                                ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\Settings.java:3: error: package POGOProtos.Networking.Responses.DownloadSettingsResponseOuterClass does not exist
import POGOProtos.Networking.Responses.DownloadSettingsResponseOuterClass.DownloadSettingsResponse;
                                                                         ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\map\Map.java:18: error: package POGOProtos.Map.MapCellOuterClass does not exist
import POGOProtos.Map.MapCellOuterClass.MapCell;
                                       ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\map\Map.java:19: error: package POGOProtos.Networking.Requests.Messages.GetMapObjectsMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.GetMapObjectsMessageOuterClass.GetMapObjectsMessage;
                                                                             ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\map\Map.java:20: error: package POGOProtos.Networking.Requests.RequestTypeOuterClass does not exist
import POGOProtos.Networking.Requests.RequestTypeOuterClass.RequestType;
                                                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\map\Map.java:21: error: package POGOProtos.Networking.Responses.GetMapObjectsResponseOuterClass does not exist
import POGOProtos.Networking.Responses.GetMapObjectsResponseOuterClass.GetMapObjectsResponse;
                                                                      ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\device\DeviceInfo.java:18: error: package POGOProtos.Networking.Envelopes does not exist
import POGOProtos.Networking.Envelopes.SignatureOuterClass;
                                      ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\device\SensorInfo.java:18: error: package POGOProtos.Networking.Envelopes does not exist
import POGOProtos.Networking.Envelopes.SignatureOuterClass;
                                      ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\device\LocationFixes.java:3: error: package POGOProtos.Networking.Envelopes does not exist
import POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass;
                                      ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\device\LocationFixes.java:4: error: package POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass does not exist
import POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass.RequestEnvelope;
                                                                ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\device\LocationFixes.java:5: error: package POGOProtos.Networking.Envelopes.SignatureOuterClass.Signature does not exist
import POGOProtos.Networking.Envelopes.SignatureOuterClass.Signature.LocationFix;
                                                                    ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\device\LocationFixes.java:6: error: package POGOProtos.Networking.Requests.RequestOuterClass does not exist
import POGOProtos.Networking.Requests.RequestOuterClass.Request;
                                                       ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\device\LocationFixes.java:7: error: package POGOProtos.Networking.Requests.RequestTypeOuterClass does not exist
import POGOProtos.Networking.Requests.RequestTypeOuterClass.RequestType;
                                                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\device\LocationFixes.java:19: error: cannot find symbol
public class LocationFixes extends ArrayList<LocationFix> {
                                             ^
  symbol: class LocationFix
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:18: error: package POGOProtos.Enums.BadgeTypeOuterClass does not exist
import POGOProtos.Enums.BadgeTypeOuterClass.BadgeType;
                                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:19: error: package POGOProtos.Enums.PokemonIdOuterClass does not exist
import POGOProtos.Enums.PokemonIdOuterClass.PokemonId;
                                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:20: error: package POGOProtos.Enums.PokemonMoveOuterClass does not exist
import POGOProtos.Enums.PokemonMoveOuterClass.PokemonMove;
                                             ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:21: error: package POGOProtos.Inventory.Item.ItemIdOuterClass does not exist
import POGOProtos.Inventory.Item.ItemIdOuterClass.ItemId;
                                                 ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:22: error: package POGOProtos.Networking.Requests.Messages.DownloadItemTemplatesMessageOuterClass does not exist
import POGOProtos.Networking.Requests.Messages.DownloadItemTemplatesMessageOuterClass.DownloadItemTemplatesMessage;
                                                                                     ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:23: error: package POGOProtos.Networking.Requests.RequestTypeOuterClass does not exist
import POGOProtos.Networking.Requests.RequestTypeOuterClass.RequestType;
                                                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:24: error: package POGOProtos.Networking.Responses.DownloadItemTemplatesResponseOuterClass does not exist
import POGOProtos.Networking.Responses.DownloadItemTemplatesResponseOuterClass.DownloadItemTemplatesResponse;
                                                                              ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:25: error: package POGOProtos.Networking.Responses.DownloadItemTemplatesResponseOuterClass.DownloadItemTemplatesResponse does not exist
import POGOProtos.Networking.Responses.DownloadItemTemplatesResponseOuterClass.DownloadItemTemplatesResponse.ItemTemplate;
                                                                                                            ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:26: error: package POGOProtos.Networking.Responses.DownloadItemTemplatesResponseOuterClass.DownloadItemTemplatesResponse does not exist
import POGOProtos.Networking.Responses.DownloadItemTemplatesResponseOuterClass.DownloadItemTemplatesResponse.Result;
                                                                                                            ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:27: error: package POGOProtos.Networking.Responses.DownloadRemoteConfigVersionResponseOuterClass does not exist
import POGOProtos.Networking.Responses.DownloadRemoteConfigVersionResponseOuterClass.DownloadRemoteConfigVersionResponse;
                                                                                    ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:28: error: package POGOProtos.Settings.Master.BadgeSettingsOuterClass does not exist
import POGOProtos.Settings.Master.BadgeSettingsOuterClass.BadgeSettings;
                                                         ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:29: error: package POGOProtos.Settings.Master.GymBattleSettingsOuterClass does not exist
import POGOProtos.Settings.Master.GymBattleSettingsOuterClass.GymBattleSettings;
                                                             ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:30: error: package POGOProtos.Settings.Master.ItemSettingsOuterClass does not exist
import POGOProtos.Settings.Master.ItemSettingsOuterClass.ItemSettings;
                                                        ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:31: error: package POGOProtos.Settings.Master.MoveSettingsOuterClass does not exist
import POGOProtos.Settings.Master.MoveSettingsOuterClass.MoveSettings;
                                                        ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:32: error: package POGOProtos.Settings.Master.PlayerLevelSettingsOuterClass does not exist
import POGOProtos.Settings.Master.PlayerLevelSettingsOuterClass.PlayerLevelSettings;
                                                               ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:33: error: package POGOProtos.Settings.Master.PokemonSettingsOuterClass does not exist
import POGOProtos.Settings.Master.PokemonSettingsOuterClass.PokemonSettings;
                                                           ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\settings\templates\ItemTemplates.java:34: error: package POGOProtos.Settings.Master.PokemonUpgradeSettingsOuterClass does not exist
import POGOProtos.Settings.Master.PokemonUpgradeSettingsOuterClass.PokemonUpgradeSettings;
                                                                  ^
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\PokemonGo.java:362: error: cannot find symbol
        public AuthInfo getAuthInfo(boolean refresh)
               ^
  symbol:   class AuthInfo
  location: class PokemonGo
L:\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\PokemonGo.java:465: error: package SignatureOuterClass.Signature does not exist
        public SignatureOuterClass.Signature.DeviceInfo getDeviceInfo() {
                                            ^
100 errors
:library:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':library:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.306 secs

**Version:**
Latest from gegy1000/PokeGOAPI-Java

**Comment by AbandonedCart** [comment]
Did you run `git submodule update --init`? It looks like the Protos may not have synced properly.

**Comment by jeremys18** [comment]
Sorry it took so long to get back. I Just tried again.

This time I cloned the project instead of just downloading it and made sure to run the submodule update --init. It worked. :D  Seems you can't skip that part and can't just download the project (it must be cloned).

Thanks!
